const SAVORA_CATALOG = [
 ['sweets',['Sweet Mix','Gulab Jamun','Kaju Katli','Laddu','Mysore Pak','Jalebi','Rasgulla','Halwa','Milk Sweet'],[200,220,300,180,250,230,260,210,280],[1,2,3,4,5,6,8,9,10],'avif'],
 ['snacks',['Murukku','Fresh Juice','Potato Chips','Mixture','Banana Chips','Healthy Mix'],[200,180,150,220,250,230],[1,2,3,4,5,6],'avif'],
 ['pickles',['Mango Pickle','Lemon Pickle','Garlic Pickle','Mixed Pickle','Tomato Pickle','Ginger Pickle'],[200,220,240,210,230,250],[1,2,3,4,5,6],null],
 ['masala',['Star Anise','Red Chili','Turmeric','Coriander','Black Pepper','Chilli Powder','Cardamom','Coriander Powder'],[200,200,200,200,200,200,200,200],[1,2,3,4,5,6,7,8],'avif'],
 ['rice',['Basmati Rice','Ponni Rice','Brown Rice','Kerala Rice','Organic Rice','Steam Rice'],[200,220,240,210,250,230],[1,2,3,4,5,7],'avif']
].flatMap(([category,names,prices,images,extension]) => names.map((name,i) => ({id:`${category}-${i+1}`,name,category,price:prices[i],image:`./assets/image/${category}/${images[i]}.${extension || (images[i] === 6 || images[i] === 8 ? 'avif' : 'jpg')}`,weight:'250 g'})));

const money = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value);
const loadCart = () => { try { return JSON.parse(localStorage.getItem('savora-cart') || '[]'); } catch { return []; } };
const saveCart = cart => { localStorage.setItem('savora-cart',JSON.stringify(cart)); updateBadges(); };
const cartCount = () => loadCart().reduce((sum,item)=>sum+item.quantity,0);
function productById(id){ return SAVORA_CATALOG.find(product=>product.id===id); }
function toast(message){ let node=document.querySelector('.savora-toast'); if(!node){node=document.createElement('div');node.className='savora-toast';document.body.append(node);} node.textContent=message;node.classList.add('show');clearTimeout(window.savoraToastTimer);window.savoraToastTimer=setTimeout(()=>node.classList.remove('show'),2400); }
function updateBadges(){ document.querySelectorAll('.savora-cart-count').forEach(node=>node.textContent=cartCount()); document.querySelectorAll('.card[data-product-id]').forEach(card=>{const item=loadCart().find(entry=>entry.id===card.dataset.productId);let label=card.querySelector('.savora-qty');if(item&&!label){label=document.createElement('span');label.className='savora-qty';card.querySelector('.card-content')?.append(label);}if(label)label.textContent=item?`${item.quantity} in cart`:'';}); }
function addToCart(id){ const cart=loadCart();const item=cart.find(entry=>entry.id===id);if(item)item.quantity=Math.min(10,item.quantity+1);else cart.push({id,quantity:1});saveCart(cart);toast(`${productById(id)?.name || 'Product'} added to cart`); }
function modal(content){const backdrop=document.createElement('div');backdrop.className='savora-modal-backdrop';backdrop.innerHTML=`<div class="savora-modal"><button class="savora-modal-close" aria-label="Close">×</button>${content}</div>`;backdrop.addEventListener('click',event=>{if(event.target===backdrop||event.target.closest('.savora-modal-close'))backdrop.remove();});document.body.append(backdrop);return backdrop;}
function showProduct(product){modal(`<div class="savora-detail"><img src="${product.image}" alt="${product.name}"><div><small>${product.category.toUpperCase()} · ${product.weight}</small><h2>${product.name}</h2><h3>${money(product.price)}</h3><p>Fresh ${product.name} prepared with carefully selected ingredients and authentic traditional flavour.</p><button class="savora-primary" data-add="${product.id}">Add to cart</button></div></div>`);}
function enhanceHeader(){const host=document.querySelector('.icons,.top-header .header-nav,.top-header');if(!host)return;const tools=document.createElement('div');tools.className='savora-tools';const user=JSON.parse(localStorage.getItem('savora-user')||'null');tools.innerHTML=`<a href="#" class="savora-account-link"><i class="fa-regular fa-user"></i> ${user?.name?.split(' ')[0]||'Login'}</a><a class="savora-cart-link" href="./cart.html"><i class="fa-solid fa-bag-shopping"></i> Cart <span class="savora-cart-count">${cartCount()}</span></a>`;if(host.classList.contains('icons'))host.replaceWith(tools);else host.append(tools);tools.querySelector('.savora-account-link').addEventListener('click',event=>{event.preventDefault();const user=JSON.parse(localStorage.getItem('savora-user')||'null');const box=modal(`<h2>${user?'Your account':'Welcome to SAVORA'}</h2>${user?`<p>Signed in as <strong>${user.name}</strong><br>${user.email}</p><button class="savora-primary" data-logout>Log out</button>`:`<form class="savora-form" data-login><label>Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><button class="savora-primary">Continue</button></form>`}`);box.querySelector('[data-login]')?.addEventListener('submit',e=>{e.preventDefault();localStorage.setItem('savora-user',JSON.stringify(Object.fromEntries(new FormData(e.target))));location.reload();});box.querySelector('[data-logout]')?.addEventListener('click',()=>{localStorage.removeItem('savora-user');location.reload();});});}
function enhanceProducts(){const category=location.pathname.split('/').pop()?.replace('.html','');if(!['sweets','snacks','pickles','masala','rice'].includes(category))return;document.querySelectorAll('.cardmg .card').forEach((card,index)=>{const product=SAVORA_CATALOG.find(item=>item.id===`${category}-${index+1}`);if(!product)return;card.dataset.productId=product.id;card.querySelector('button')?.addEventListener('click',event=>{event.preventDefault();addToCart(product.id);});card.querySelector('img')?.addEventListener('click',()=>showProduct(product));card.querySelector('h3')?.addEventListener('click',()=>showProduct(product));});}
function enhanceSearch(){document.querySelectorAll('.search-box').forEach(box=>{const input=box.querySelector('input');if(!input)return;box.style.position='relative';const results=document.createElement('div');results.className='savora-search-results';results.hidden=true;box.append(results);const render=()=>{const q=input.value.trim().toLowerCase();document.querySelectorAll('.cardmg .card').forEach(card=>card.style.display=!q||card.textContent.toLowerCase().includes(q)?'':'none');if(!q){results.hidden=true;return;}const matches=SAVORA_CATALOG.filter(item=>`${item.name} ${item.category}`.toLowerCase().includes(q)).slice(0,7);results.innerHTML=matches.length?matches.map(item=>`<a class="savora-search-item" href="./${item.category}.html?product=${item.id}"><img src="${item.image}"><span><strong>${item.name}</strong><br><small>${item.category}</small></span><b>${money(item.price)}</b></a>`).join(''):'<div class="savora-search-empty">No products found.</div>';results.hidden=false;};input.addEventListener('input',render);input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();results.querySelector('a')?.click();}});document.addEventListener('click',event=>{if(!box.contains(event.target))results.hidden=true;});});}
function enhanceForms(){const contact=document.querySelector('.contact-form form');if(contact)contact.addEventListener('submit',async event=>{event.preventDefault();const fields=[...contact.querySelectorAll('input,textarea')];const payload={name:fields[0].value,email:fields[1].value,subject:fields[2].value,message:fields[3].value};try{const res=await fetch('./api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.message);toast(data.message);contact.reset();}catch(error){if(location.hostname.endsWith('github.io')){toast('Thank you. We will get back to you soon.');contact.reset();}else toast(error.message);}});document.querySelectorAll('.newsletter').forEach(form=>{const button=form.querySelector('button'),input=form.querySelector('input');button?.addEventListener('click',async()=>{if(!/^\S+@\S+\.\S+$/.test(input.value)){toast('Enter a valid email address.');return;}try{await fetch('./api/newsletter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:input.value})});}catch{}toast('You are subscribed to SAVORA updates.');input.value='';});});}
document.addEventListener('click',event=>{const add=event.target.closest('[data-add]');if(add)addToCart(add.dataset.add);});
document.addEventListener('DOMContentLoaded',()=>{enhanceHeader();enhanceProducts();enhanceSearch();enhanceForms();updateBadges();const target=new URLSearchParams(location.search).get('product');if(target)setTimeout(()=>showProduct(productById(target)),100);});
